### ISSUE TITLE
Snow Lands

### ISSUE THREAD

**Issue by 7stringplayer** [arxanas/drafts.ninja#42] opened 2016-08-31 03:13 UTC
Any way snow lands can be added to Coldsnap packs.  They showed up as common slot in Coldsnap.  This will help with chaos drafts and random drafts .

**Comment by tooomm** [comment] 2016-09-09 08:41
@arxanas Once the `Tag` is in the starting post instead it'll work as intended: https://github.com/arxanas/drafts.ninja/pull/43#issuecomment-243662904

https://help.github.com/articles/closing-issues-via-commit-messages/

**Closed as completed** 2016-09-09 17:30 UTC
